# Generated by Django 5.1.6 on 2026-09-13 13:08

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Владелец"),
                            ("head", "Руководитель"),
                            ("metrologist", "Метролог / нормоконтроль"),
                            ("manager", "Менеджер"),
                            ("verifier", "Поверитель"),
                            ("observer", "Наблюдатель"),
                        ],
                        default="observer",
                        max_length=20,
                        verbose_name="роль",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "пользователь",
                "verbose_name_plural": "пользователи",
            },
            managers=[
                ("objects", apps.core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tab_number",
                    models.CharField(
                        max_length=8, unique=True, verbose_name="табельный номер"
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="ФИО")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="ФИО сокращённо"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="должность"
                    ),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True, upload_to="signatures/", verbose_name="подпись"
                    ),
                ),
                (
                    "stamp_image",
                    models.ImageField(
                        blank=True, upload_to="stamps/", verbose_name="оттиск клейма"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="работает"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="учётная запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "сотрудник",
                "verbose_name_plural": "сотрудники",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="идентификатор"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="название"
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="последняя синхронизация"
                    ),
                ),
                (
                    "last_sync_cursor",
                    models.BigIntegerField(
                        default=0, verbose_name="курсор синхронизации"
                    ),
                ),
                (
                    "is_revoked",
                    models.BooleanField(default=False, verbose_name="отозвано"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="core.employee",
                        verbose_name="сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "устройство",
                "verbose_name_plural": "устройства",
            },
        ),
        migrations.CreateModel(
            name="Attestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document", models.CharField(max_length=120, verbose_name="документ")),
                ("valid_from", models.DateField(verbose_name="действует с")),
                ("valid_to", models.DateField(verbose_name="действует по")),
                (
                    "scan",
                    models.FileField(
                        blank=True, upload_to="attestations/", verbose_name="скан"
                    ),
                ),
                (
                    "families",
                    models.ManyToManyField(
                        related_name="attestations",
                        to="catalog.measurementfamily",
                        verbose_name="семейства СИ",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attestations",
                        to="core.employee",
                        verbose_name="сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "аттестация",
                "verbose_name_plural": "аттестации",
                "ordering": ["-valid_to"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalAttestation",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("document", models.CharField(max_length=120, verbose_name="документ")),
                ("valid_from", models.DateField(verbose_name="действует с")),
                ("valid_to", models.DateField(verbose_name="действует по")),
                (
                    "scan",
                    models.TextField(blank=True, max_length=100, verbose_name="скан"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.employee",
                        verbose_name="сотрудник",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical аттестация",
                "verbose_name_plural": "historical аттестации",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEmployee",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "tab_number",
                    models.CharField(
                        db_index=True, max_length=8, verbose_name="табельный номер"
                    ),
                ),
                ("full_name", models.CharField(max_length=200, verbose_name="ФИО")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="ФИО сокращённо"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="должность"
                    ),
                ),
                (
                    "signature_image",
                    models.TextField(
                        blank=True, max_length=100, verbose_name="подпись"
                    ),
                ),
                (
                    "stamp_image",
                    models.TextField(
                        blank=True, max_length=100, verbose_name="оттиск клейма"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="работает"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="учётная запись",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical сотрудник",
                "verbose_name_plural": "historical сотрудники",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
