# Generated by Django 5.1.6 on 2026-09-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Сотрудник пишет боту /start, chat_id из апдейта вносится сюда руками — привязки по номеру телефона нет', max_length=32, verbose_name='Telegram chat_id'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Сотрудник пишет боту /start, chat_id из апдейта вносится сюда руками — привязки по номеру телефона нет', max_length=32, verbose_name='Telegram chat_id'),
        ),
    ]
