# Generated by Django 5.1.6 on 2026-09-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='telegram_link_code',
            field=models.CharField(blank=True, help_text='Сотрудник получает его в своём профиле в EI_doc и присылает боту командой /start <код>; код одноразовый и живёт 15 минут', max_length=8, verbose_name='код привязки Telegram'),
        ),
        migrations.AddField(
            model_name='employee',
            name='telegram_link_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='код привязки действует до'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='telegram_link_code',
            field=models.CharField(blank=True, help_text='Сотрудник получает его в своём профиле в EI_doc и присылает боту командой /start <код>; код одноразовый и живёт 15 минут', max_length=8, verbose_name='код привязки Telegram'),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='telegram_link_code_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='код привязки действует до'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Заполняется само, когда сотрудник привязывает Telegram кодом (см. telegram_link_code) — руками трогать не нужно', max_length=32, verbose_name='Telegram chat_id'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Заполняется само, когда сотрудник привязывает Telegram кодом (см. telegram_link_code) — руками трогать не нужно', max_length=32, verbose_name='Telegram chat_id'),
        ),
    ]
