# Generated by Django 5.1.6 on 2026-09-13 13:08

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("person", "Частное лицо"),
                            ("org", "Юридическое лицо"),
                        ],
                        default="person",
                        max_length=10,
                        verbose_name="тип",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="наименование / ФИО"),
                ),
                (
                    "inn",
                    models.CharField(
                        blank=True, db_index=True, max_length=12, verbose_name="ИНН"
                    ),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=32, verbose_name="телефон"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("note", models.TextField(blank=True, verbose_name="примечание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "клиент",
                "verbose_name_plural": "клиенты",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Instrument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=60, verbose_name="заводской номер"),
                ),
                (
                    "manufacture_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="год выпуска"
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="доп. характеристики"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instruments",
                        to="verification.client",
                        verbose_name="владелец",
                    ),
                ),
                (
                    "si_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instruments",
                        to="catalog.sitype",
                        verbose_name="тип СИ",
                    ),
                ),
            ],
            options={
                "verbose_name": "экземпляр СИ",
                "verbose_name_plural": "экземпляры СИ",
            },
        ),
        migrations.CreateModel(
            name="HistoricalVerification",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        verbose_name="идентификатор с устройства",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Определяет порядковый номер протокола — номера идут строго по времени поверки",
                        verbose_name="дата и время поверки",
                    ),
                ),
                (
                    "next_verification_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="следующая поверка"
                    ),
                ),
                (
                    "suitable",
                    models.BooleanField(default=True, verbose_name="признан годным"),
                ),
                (
                    "unsuitability_reason",
                    models.TextField(blank=True, verbose_name="причины непригодности"),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="температура, °C",
                    ),
                ),
                (
                    "temperature_source",
                    models.CharField(
                        choices=[
                            ("measured", "Измерено"),
                            ("archive", "Метеоархив"),
                            ("default", "Норматив по умолчанию"),
                        ],
                        default="measured",
                        max_length=10,
                    ),
                ),
                (
                    "pressure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="давление, кПа",
                    ),
                ),
                (
                    "pressure_source",
                    models.CharField(
                        choices=[
                            ("measured", "Измерено"),
                            ("archive", "Метеоархив"),
                            ("default", "Норматив по умолчанию"),
                        ],
                        default="measured",
                        max_length=10,
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="влажность, %",
                    ),
                ),
                (
                    "humidity_source",
                    models.CharField(
                        choices=[
                            ("measured", "Измерено"),
                            ("archive", "Метеоархив"),
                            ("default", "Норматив по умолчанию"),
                        ],
                        default="measured",
                        max_length=10,
                    ),
                ),
                (
                    "measurements",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Структура задаётся MeasurementFamily.measurement_schema",
                        verbose_name="измерения",
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Заполняется калькулятором семейства, не руками",
                        verbose_name="результаты расчёта",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("ready", "Готова к нормоконтролю"),
                            ("accepted", "Принята"),
                            ("rejected", "Возвращена на доработку"),
                        ],
                        default="draft",
                        max_length=12,
                        verbose_name="статус",
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True, verbose_name="замечание нормоконтроля"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        verbose_name="создана",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="изменена"
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="синхронизирована"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.device",
                        verbose_name="устройство",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.verificationmethod",
                        verbose_name="методика",
                    ),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.employee",
                        verbose_name="поверитель",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verification.instrument",
                        verbose_name="СИ",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical поверка",
                "verbose_name_plural": "historical поверки",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="NumberingScope",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Заполняется, только если у семейства включён ежегодный сброс нумерации",
                        null=True,
                        verbose_name="год",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="numbering_scopes",
                        to="core.employee",
                        verbose_name="поверитель",
                    ),
                ),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="numbering_scopes",
                        to="catalog.measurementfamily",
                        verbose_name="семейство",
                    ),
                ),
            ],
            options={
                "verbose_name": "область нумерации",
                "verbose_name_plural": "области нумерации",
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=350, verbose_name="адрес")),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="долгота",
                    ),
                ),
                (
                    "is_restricted",
                    models.BooleanField(
                        default=False,
                        help_text="Телефон пронести нельзя — работа по бумажному бланку",
                        verbose_name="режимный объект",
                    ),
                ),
                (
                    "access_note",
                    models.TextField(blank=True, verbose_name="порядок допуска"),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="контактное лицо"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sites",
                        to="verification.client",
                        verbose_name="клиент",
                    ),
                ),
            ],
            options={
                "verbose_name": "объект",
                "verbose_name_plural": "объекты",
                "ordering": ["address"],
            },
        ),
        migrations.AddField(
            model_name="instrument",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instruments",
                to="verification.site",
                verbose_name="место установки",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalInstrument",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(max_length=60, verbose_name="заводской номер"),
                ),
                (
                    "manufacture_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="год выпуска"
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="доп. характеристики"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verification.client",
                        verbose_name="владелец",
                    ),
                ),
                (
                    "si_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.sitype",
                        verbose_name="тип СИ",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verification.site",
                        verbose_name="место установки",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical экземпляр СИ",
                "verbose_name_plural": "historical экземпляры СИ",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        unique=True,
                        verbose_name="идентификатор с устройства",
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Определяет порядковый номер протокола — номера идут строго по времени поверки",
                        verbose_name="дата и время поверки",
                    ),
                ),
                (
                    "next_verification_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="следующая поверка"
                    ),
                ),
                (
                    "suitable",
                    models.BooleanField(default=True, verbose_name="признан годным"),
                ),
                (
                    "unsuitability_reason",
                    models.TextField(blank=True, verbose_name="причины непригодности"),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="температура, °C",
                    ),
                ),
                (
                    "temperature_source",
                    models.CharField(
                        choices=[
                            ("measured", "Измерено"),
                            ("archive", "Метеоархив"),
                            ("default", "Норматив по умолчанию"),
                        ],
                        default="measured",
                        max_length=10,
                    ),
                ),
                (
                    "pressure",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=6,
                        null=True,
                        verbose_name="давление, кПа",
                    ),
                ),
                (
                    "pressure_source",
                    models.CharField(
                        choices=[
                            ("measured", "Измерено"),
                            ("archive", "Метеоархив"),
                            ("default", "Норматив по умолчанию"),
                        ],
                        default="measured",
                        max_length=10,
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="влажность, %",
                    ),
                ),
                (
                    "humidity_source",
                    models.CharField(
                        choices=[
                            ("measured", "Измерено"),
                            ("archive", "Метеоархив"),
                            ("default", "Норматив по умолчанию"),
                        ],
                        default="measured",
                        max_length=10,
                    ),
                ),
                (
                    "measurements",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Структура задаётся MeasurementFamily.measurement_schema",
                        verbose_name="измерения",
                    ),
                ),
                (
                    "results",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Заполняется калькулятором семейства, не руками",
                        verbose_name="результаты расчёта",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("ready", "Готова к нормоконтролю"),
                            ("accepted", "Принята"),
                            ("rejected", "Возвращена на доработку"),
                        ],
                        default="draft",
                        max_length=12,
                        verbose_name="статус",
                    ),
                ),
                (
                    "review_note",
                    models.TextField(
                        blank=True, verbose_name="замечание нормоконтроля"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="создана"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="изменена"),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="синхронизирована"
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verifications",
                        to="core.device",
                        verbose_name="устройство",
                    ),
                ),
                (
                    "instrument",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verifications",
                        to="verification.instrument",
                        verbose_name="СИ",
                    ),
                ),
                (
                    "method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verifications",
                        to="catalog.verificationmethod",
                        verbose_name="методика",
                    ),
                ),
                (
                    "standards",
                    models.ManyToManyField(
                        related_name="verifications",
                        to="catalog.standard",
                        verbose_name="применённые эталоны",
                    ),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="verifications",
                        to="core.employee",
                        verbose_name="поверитель",
                    ),
                ),
            ],
            options={
                "verbose_name": "поверка",
                "verbose_name_plural": "поверки",
                "ordering": ["-verified_at"],
            },
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seq",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="NULL у черновика. Пересчитывается, пока протокол не подписан",
                        null=True,
                        verbose_name="порядковый номер",
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Для вставки задним числом в уже запечатанный участок: 0147А",
                        max_length=2,
                        verbose_name="литера",
                    ),
                ),
                (
                    "out_of_sequence_reason",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="причина вставки вне очереди",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("numbered", "Номер присвоен"),
                            ("signed", "Подписан"),
                            ("published", "Опубликован в ФИФ"),
                            ("void", "Аннулирован"),
                        ],
                        default="draft",
                        max_length=12,
                        verbose_name="статус",
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True, upload_to="protocols/%Y/%m/", verbose_name="PDF"
                    ),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="SHA-256 файла"
                    ),
                ),
                (
                    "numbered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="номер присвоен"
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="подписан"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="опубликован в ФИФ"
                    ),
                ),
                (
                    "fif_record_number",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="номер записи в ФИФ"
                    ),
                ),
                (
                    "void_reason",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="причина аннулирования"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="protocols",
                        to="verification.numberingscope",
                        verbose_name="область нумерации",
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signed_protocols",
                        to="core.employee",
                        verbose_name="подписал",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="superseded_by",
                        to="verification.protocol",
                        verbose_name="заменяет протокол",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="protocols",
                        to="catalog.protocoltemplate",
                        verbose_name="версия шаблона",
                    ),
                ),
                (
                    "verification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="protocol",
                        to="verification.verification",
                        verbose_name="поверка",
                    ),
                ),
            ],
            options={
                "verbose_name": "протокол",
                "verbose_name_plural": "протоколы",
                "ordering": ["scope", "seq", "suffix"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalProtocol",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "seq",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="NULL у черновика. Пересчитывается, пока протокол не подписан",
                        null=True,
                        verbose_name="порядковый номер",
                    ),
                ),
                (
                    "suffix",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Для вставки задним числом в уже запечатанный участок: 0147А",
                        max_length=2,
                        verbose_name="литера",
                    ),
                ),
                (
                    "out_of_sequence_reason",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        verbose_name="причина вставки вне очереди",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("numbered", "Номер присвоен"),
                            ("signed", "Подписан"),
                            ("published", "Опубликован в ФИФ"),
                            ("void", "Аннулирован"),
                        ],
                        default="draft",
                        max_length=12,
                        verbose_name="статус",
                    ),
                ),
                (
                    "pdf",
                    models.TextField(blank=True, max_length=100, verbose_name="PDF"),
                ),
                (
                    "sha256",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="SHA-256 файла"
                    ),
                ),
                (
                    "numbered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="номер присвоен"
                    ),
                ),
                (
                    "signed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="подписан"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="опубликован в ФИФ"
                    ),
                ),
                (
                    "fif_record_number",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="номер записи в ФИФ"
                    ),
                ),
                (
                    "void_reason",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="причина аннулирования"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.employee",
                        verbose_name="подписал",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="catalog.protocoltemplate",
                        verbose_name="версия шаблона",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verification.numberingscope",
                        verbose_name="область нумерации",
                    ),
                ),
                (
                    "supersedes",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verification.protocol",
                        verbose_name="заменяет протокол",
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="verification.verification",
                        verbose_name="поверка",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical протокол",
                "verbose_name_plural": "historical протоколы",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="numberingscope",
            constraint=models.UniqueConstraint(
                fields=("family", "employee", "year"),
                name="numberingscope_unique",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="instrument",
            constraint=models.UniqueConstraint(
                fields=("si_type", "serial_number"),
                name="instrument_unique_type_serial",
            ),
        ),
        migrations.AddIndex(
            model_name="verification",
            index=models.Index(
                fields=["verifier", "verified_at"],
                name="verificatio_verifie_8b9275_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="protocol",
            index=models.Index(
                fields=["scope", "status"], name="verificatio_scope_i_6a563b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="protocol",
            constraint=models.UniqueConstraint(
                condition=models.Q(("seq__isnull", False)),
                fields=("scope", "seq", "suffix"),
                name="protocol_unique_number",
            ),
        ),
    ]
