# Generated by Django 5.1.6 on 2026-09-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprotocol",
            name="field_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Когда у поверителя на объекте нет доступа к базе, на свидетельстве пишется номер «на месте». Здесь он сохраняется и связывается с настоящим — иначе бумагу на руках у клиента потом не найти",
                max_length=40,
                verbose_name="номер, записанный на свидетельстве в поле",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="field_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Когда у поверителя на объекте нет доступа к базе, на свидетельстве пишется номер «на месте». Здесь он сохраняется и связывается с настоящим — иначе бумагу на руках у клиента потом не найти",
                max_length=40,
                verbose_name="номер, записанный на свидетельстве в поле",
            ),
        ),
        migrations.AlterField(
            model_name="historicalverification",
            name="humidity_source",
            field=models.CharField(
                choices=[
                    ("measured", "Измерено"),
                    ("archive", "Из журнала погоды"),
                    ("generated", "Сгенерировано в нормативном диапазоне"),
                ],
                default="measured",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalverification",
            name="pressure_source",
            field=models.CharField(
                choices=[
                    ("measured", "Измерено"),
                    ("archive", "Из журнала погоды"),
                    ("generated", "Сгенерировано в нормативном диапазоне"),
                ],
                default="measured",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalverification",
            name="temperature_source",
            field=models.CharField(
                choices=[
                    ("measured", "Измерено"),
                    ("archive", "Из журнала погоды"),
                    ("generated", "Сгенерировано в нормативном диапазоне"),
                ],
                default="measured",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="numberingscope",
            name="year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Счётчик сбрасывается в начале года, поэтому область нумерации — годовая. NULL только у семейств со сквозной нумерацией",
                null=True,
                verbose_name="год",
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="humidity_source",
            field=models.CharField(
                choices=[
                    ("measured", "Измерено"),
                    ("archive", "Из журнала погоды"),
                    ("generated", "Сгенерировано в нормативном диапазоне"),
                ],
                default="measured",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="pressure_source",
            field=models.CharField(
                choices=[
                    ("measured", "Измерено"),
                    ("archive", "Из журнала погоды"),
                    ("generated", "Сгенерировано в нормативном диапазоне"),
                ],
                default="measured",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="verification",
            name="temperature_source",
            field=models.CharField(
                choices=[
                    ("measured", "Измерено"),
                    ("archive", "Из журнала погоды"),
                    ("generated", "Сгенерировано в нормативном диапазоне"),
                ],
                default="measured",
                max_length=10,
            ),
        ),
    ]
