# Generated by Django 5.1.6 on 2026-09-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalverification",
            name="needs_review",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Распознано неуверенно или объём по эталону разошёлся с расчётным. Признак вынесен из JSON отдельным полем — по нему фильтруется журнал",
                verbose_name="есть строки на сверку",
            ),
        ),
        migrations.AddField(
            model_name="verification",
            name="needs_review",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Распознано неуверенно или объём по эталону разошёлся с расчётным. Признак вынесен из JSON отдельным полем — по нему фильтруется журнал",
                verbose_name="есть строки на сверку",
            ),
        ),
    ]
