# Generated by Django 5.1.6 on 2026-09-15 07:56

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_district'),
        ('core', '0002_employee_telegram_chat_id_and_more'),
        ('hub', '0001_initial'),
        ('verification', '0002_historicalverification_needs_review_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='catalog.district', verbose_name='район'),
        ),
        migrations.AddField(
            model_name='site',
            name='fias_id',
            field=models.CharField(blank=True, help_text='Заполняется, когда адрес выбран из подсказки (DaData), а не введён вручную', max_length=64, verbose_name='ФИАС ID'),
        ),
        migrations.AddField(
            model_name='site',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='индекс'),
        ),
        migrations.CreateModel(
            name='HistoricalWorkOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('in_progress', 'В работе'), ('done', 'Закрыт'), ('cancelled', 'Отменён')], default='planned', max_length=12, verbose_name='статус')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='плановая дата')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='создан')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='закрыт')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('assigned_employee', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.employee', verbose_name='исполнитель')),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='verification.client', verbose_name='клиент')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, db_constraint=False, help_text='Пусто, если наряд заведён напрямую, не из заявки с сайта', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hub.request', verbose_name='заявка')),
                ('site', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='verification.site', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'historical наряд',
                'verbose_name_plural': 'historical наряды',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('in_progress', 'В работе'), ('done', 'Закрыт'), ('cancelled', 'Отменён')], default='planned', max_length=12, verbose_name='статус')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='плановая дата')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='закрыт')),
                ('assigned_employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='core.employee', verbose_name='исполнитель')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='verification.client', verbose_name='клиент')),
                ('request', models.ForeignKey(blank=True, help_text='Пусто, если наряд заведён напрямую, не из заявки с сайта', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='hub.request', verbose_name='заявка')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='verification.site', verbose_name='объект')),
            ],
            options={
                'verbose_name': 'наряд',
                'verbose_name_plural': 'наряды',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='historicalverification',
            name='work_order',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Пусто, если поверка заведена не из наряда (например, импорт истории)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='verification.workorder', verbose_name='наряд'),
        ),
        migrations.AddField(
            model_name='verification',
            name='work_order',
            field=models.ForeignKey(blank=True, help_text='Пусто, если поверка заведена не из наряда (например, импорт истории)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='verification.workorder', verbose_name='наряд'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status', 'scheduled_date'], name='verificatio_status_e0c537_idx'),
        ),
    ]
