# Generated by Django 5.1.6 on 2026-09-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0003_site_district_site_fias_id_site_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkorder',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Переносится из Request.desired_time при подтверждении заявки, если среди приборов был хоть один, требующий выбора времени', null=True, verbose_name='плановое время'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='scheduled_time',
            field=models.TimeField(blank=True, help_text='Переносится из Request.desired_time при подтверждении заявки, если среди приборов был хоть один, требующий выбора времени', null=True, verbose_name='плановое время'),
        ),
    ]
