# Generated by Django 5.1.6 on 2026-09-16 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_employee_telegram_link_code_and_more'),
        ('verification', '0004_historicalworkorder_scheduled_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='scans/%Y/%m/', verbose_name='фото бланка')),
                ('recognized', models.JSONField(blank=True, default=dict, help_text='Сырой ответ распознавания — для отладки и метрики доли строк, исправленных человеком на экране сверки', verbose_name='распознано VLM')),
                ('error', models.TextField(blank=True, help_text='QR не найден, реперные метки не выровнялись, распознавание недоступно и т. п. — поверитель в этом случае вводит вручную', verbose_name='ошибка обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_uploads', to='core.employee', verbose_name='загрузил')),
                ('verification', models.ForeignKey(blank=True, help_text='Заполняется после распознавания — какую поверку завела эта фотография', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='verification.verification', verbose_name='поверка')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='verification.workorder', verbose_name='наряд')),
            ],
            options={
                'verbose_name': 'скан бланка',
                'verbose_name_plural': 'сканы бланков',
                'ordering': ['-created_at'],
            },
        ),
    ]
