# Generated by Django 5.1.6 on 2026-09-16 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_employee_telegram_link_code_and_more"),
        ("verification", "0005_scanupload"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="verification_photos/%Y/%m/", verbose_name="фото"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="подпись"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создано"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verification_photos",
                        to="core.employee",
                        verbose_name="загрузил",
                    ),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="verification.verification",
                        verbose_name="поверка",
                    ),
                ),
            ],
            options={
                "verbose_name": "фото СИ",
                "verbose_name_plural": "фото СИ",
                "ordering": ["created_at"],
            },
        ),
    ]
