# Generated by Django 5.1.6 on 2026-09-14 07:26

import django.core.validators
import django.utils.timezone
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AmbientRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="дата")),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="температура, °C"
                    ),
                ),
                (
                    "pressure",
                    models.DecimalField(
                        decimal_places=1, max_digits=6, verbose_name="давление, кПа"
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="влажность, %"
                    ),
                ),
                (
                    "is_generated",
                    models.BooleanField(
                        default=True,
                        help_text="Снято, если значения занесены как реально измеренные",
                        verbose_name="сгенерировано",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "запись журнала погоды",
                "verbose_name_plural": "журнал погоды",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ConditionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Основной", max_length=120, verbose_name="название"
                    ),
                ),
                (
                    "ranges",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="диапазоны"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
            ],
            options={
                "verbose_name": "профиль условий поверки",
                "verbose_name_plural": "профили условий поверки",
            },
        ),
        migrations.CreateModel(
            name="HistoricalConditionProfile",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Основной", max_length=120, verbose_name="название"
                    ),
                ),
                (
                    "ranges",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="диапазоны"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical профиль условий поверки",
                "verbose_name_plural": "historical профили условий поверки",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalMeasurementFamily",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("code", models.SlugField(max_length=40, verbose_name="код")),
                ("name", models.CharField(max_length=160, verbose_name="наименование")),
                (
                    "measurement_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Проверяет структуру Verification.measurements для этого семейства",
                        verbose_name="JSON Schema измерений",
                    ),
                ),
                (
                    "calculator_key",
                    models.CharField(
                        blank=True,
                        help_text="Имя модуля расчёта, например water_meter",
                        max_length=60,
                        verbose_name="ключ калькулятора",
                    ),
                ),
                (
                    "condition_ranges",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Переопределяет общий профиль условий для этого семейства, см. apps.catalog.conditions",
                        verbose_name="диапазоны условий поверки",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical семейство СИ",
                "verbose_name_plural": "historical семейства СИ",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalNumberingSeries",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{2}$", "Две цифры, например 03"
                            )
                        ],
                        verbose_name="код",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="название")),
                (
                    "digits",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="ЕИ-03-02-00767 — пять",
                        verbose_name="разрядов в порядковом номере",
                    ),
                ),
                (
                    "resets_yearly",
                    models.BooleanField(
                        default=True, verbose_name="сбрасывается в начале года"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Используется семействами СИ, у которых серия не указана явно",
                        verbose_name="по умолчанию",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical серия нумерации",
                "verbose_name_plural": "historical серии нумерации",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProtocolTemplate",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="версия")),
                ("source", models.TextField(verbose_name="исходник Typst")),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="что изменилось"
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="применяется с",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="создана"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical шаблон протокола",
                "verbose_name_plural": "historical шаблоны протоколов",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalSiType",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "registry_number",
                    models.CharField(
                        max_length=40, verbose_name="регистрационный номер"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="наименование")),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="изготовитель"
                    ),
                ),
                (
                    "verification_interval_months",
                    models.PositiveSmallIntegerField(
                        default=72, verbose_name="межповерочный интервал, мес."
                    ),
                ),
                ("fif_url", models.URLField(blank=True, verbose_name="ссылка на ФИФ")),
                (
                    "fif_raw",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="ответ ФИФ как есть"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="используется"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical тип СИ",
                "verbose_name_plural": "historical типы СИ",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalStandard",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "fif_number",
                    models.CharField(
                        db_index=True, max_length=60, verbose_name="номер в ФИФ"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="наименование")),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="заводской номер"
                    ),
                ),
                ("verified_at", models.DateField(verbose_name="поверен")),
                ("valid_until", models.DateField(verbose_name="годен до")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="где находится"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="в работе"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical эталон",
                "verbose_name_plural": "historical эталоны",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MeasurementFamily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(max_length=40, unique=True, verbose_name="код"),
                ),
                ("name", models.CharField(max_length=160, verbose_name="наименование")),
                (
                    "measurement_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Проверяет структуру Verification.measurements для этого семейства",
                        verbose_name="JSON Schema измерений",
                    ),
                ),
                (
                    "calculator_key",
                    models.CharField(
                        blank=True,
                        help_text="Имя модуля расчёта, например water_meter",
                        max_length=60,
                        verbose_name="ключ калькулятора",
                    ),
                ),
                (
                    "condition_ranges",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Переопределяет общий профиль условий для этого семейства, см. apps.catalog.conditions",
                        verbose_name="диапазоны условий поверки",
                    ),
                ),
            ],
            options={
                "verbose_name": "семейство СИ",
                "verbose_name_plural": "семейства СИ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="NumberingSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=2,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{2}$", "Две цифры, например 03"
                            )
                        ],
                        verbose_name="код",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="название")),
                (
                    "digits",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="ЕИ-03-02-00767 — пять",
                        verbose_name="разрядов в порядковом номере",
                    ),
                ),
                (
                    "resets_yearly",
                    models.BooleanField(
                        default=True, verbose_name="сбрасывается в начале года"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="Используется семействами СИ, у которых серия не указана явно",
                        verbose_name="по умолчанию",
                    ),
                ),
            ],
            options={
                "verbose_name": "серия нумерации",
                "verbose_name_plural": "серии нумерации",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ProtocolTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="версия")),
                ("source", models.TextField(verbose_name="исходник Typst")),
                (
                    "comment",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="что изменилось"
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        verbose_name="применяется с",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активна"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создана"),
                ),
            ],
            options={
                "verbose_name": "шаблон протокола",
                "verbose_name_plural": "шаблоны протоколов",
                "ordering": ["family", "-version"],
            },
        ),
        migrations.CreateModel(
            name="SiType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registry_number",
                    models.CharField(
                        max_length=40, verbose_name="регистрационный номер"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="наименование")),
                (
                    "manufacturer",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="изготовитель"
                    ),
                ),
                (
                    "verification_interval_months",
                    models.PositiveSmallIntegerField(
                        default=72, verbose_name="межповерочный интервал, мес."
                    ),
                ),
                ("fif_url", models.URLField(blank=True, verbose_name="ссылка на ФИФ")),
                (
                    "fif_raw",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="ответ ФИФ как есть"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="используется"),
                ),
            ],
            options={
                "verbose_name": "тип СИ",
                "verbose_name_plural": "типы СИ",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Standard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fif_number",
                    models.CharField(
                        max_length=60, unique=True, verbose_name="номер в ФИФ"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="наименование")),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="заводской номер"
                    ),
                ),
                ("verified_at", models.DateField(verbose_name="поверен")),
                ("valid_until", models.DateField(verbose_name="годен до")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="где находится"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="в работе"),
                ),
            ],
            options={
                "verbose_name": "эталон",
                "verbose_name_plural": "эталоны",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="VerificationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="обозначение"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="наименование"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True, upload_to="methods/", verbose_name="документ"
                    ),
                ),
            ],
            options={
                "verbose_name": "методика поверки",
                "verbose_name_plural": "методики поверки",
                "ordering": ["designation"],
            },
        ),
    ]
