# Generated by Django 5.1.6 on 2026-09-14 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalconditionprofile",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalmeasurementfamily",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalnumberingseries",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocoltemplate",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsitype",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalstandard",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalsitype",
            name="family",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="catalog.measurementfamily",
                verbose_name="семейство",
            ),
        ),
        migrations.AddField(
            model_name="historicalprotocoltemplate",
            name="family",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="catalog.measurementfamily",
                verbose_name="семейство",
            ),
        ),
        migrations.AddField(
            model_name="measurementfamily",
            name="numbering_series",
            field=models.ForeignKey(
                blank=True,
                help_text="Пусто — берётся серия по умолчанию. Несколько семейств СИ в одной серии делят общий счётчик протоколов",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="families",
                to="catalog.numberingseries",
                verbose_name="серия нумерации",
            ),
        ),
        migrations.AddField(
            model_name="historicalmeasurementfamily",
            name="numbering_series",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Пусто — берётся серия по умолчанию. Несколько семейств СИ в одной серии делят общий счётчик протоколов",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="catalog.numberingseries",
                verbose_name="серия нумерации",
            ),
        ),
        migrations.AddField(
            model_name="protocoltemplate",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="templates",
                to="catalog.measurementfamily",
                verbose_name="семейство",
            ),
        ),
        migrations.AddField(
            model_name="sitype",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="si_types",
                to="catalog.measurementfamily",
                verbose_name="семейство",
            ),
        ),
        migrations.AddField(
            model_name="verificationmethod",
            name="families",
            field=models.ManyToManyField(
                related_name="methods",
                to="catalog.measurementfamily",
                verbose_name="семейства СИ",
            ),
        ),
        migrations.AddConstraint(
            model_name="protocoltemplate",
            constraint=models.UniqueConstraint(
                fields=("family", "version"),
                name="protocoltemplate_unique_family_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="sitype",
            constraint=models.UniqueConstraint(
                fields=("registry_number", "name"), name="sitype_unique_registry_name"
            ),
        ),
    ]
