# Generated by Django 5.1.6 on 2026-09-13 14:09

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AmbientRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="дата")),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="температура, °C"
                    ),
                ),
                (
                    "pressure",
                    models.DecimalField(
                        decimal_places=1, max_digits=6, verbose_name="давление, кПа"
                    ),
                ),
                (
                    "humidity",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="влажность, %"
                    ),
                ),
                (
                    "is_generated",
                    models.BooleanField(
                        default=True,
                        help_text="Снято, если значения занесены как реально измеренные",
                        verbose_name="сгенерировано",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "запись журнала погоды",
                "verbose_name_plural": "журнал погоды",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ConditionProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Основной", max_length=120, verbose_name="название"
                    ),
                ),
                (
                    "ranges",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="диапазоны"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
            ],
            options={
                "verbose_name": "профиль условий поверки",
                "verbose_name_plural": "профили условий поверки",
            },
        ),
        migrations.RemoveField(
            model_name="historicalmeasurementfamily",
            name="uses_number_blocks",
        ),
        migrations.RemoveField(
            model_name="measurementfamily",
            name="uses_number_blocks",
        ),
        migrations.AddField(
            model_name="historicalmeasurementfamily",
            name="condition_ranges",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Переопределяет общий профиль условий для этого семейства, см. apps.catalog.conditions",
                verbose_name="диапазоны условий поверки",
            ),
        ),
        migrations.AddField(
            model_name="historicalmeasurementfamily",
            name="number_digits",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="ЕИ-03-02-00772 — пять разрядов",
                verbose_name="разрядов в номере протокола",
            ),
        ),
        migrations.AddField(
            model_name="measurementfamily",
            name="condition_ranges",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Переопределяет общий профиль условий для этого семейства, см. apps.catalog.conditions",
                verbose_name="диапазоны условий поверки",
            ),
        ),
        migrations.AddField(
            model_name="measurementfamily",
            name="number_digits",
            field=models.PositiveSmallIntegerField(
                default=5,
                help_text="ЕИ-03-02-00772 — пять разрядов",
                verbose_name="разрядов в номере протокола",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmeasurementfamily",
            name="numbering_resets_yearly",
            field=models.BooleanField(
                default=True,
                help_text="Счётчик протоколов обнуляется 1 января",
                verbose_name="нумерация сбрасывается в начале года",
            ),
        ),
        migrations.AlterField(
            model_name="measurementfamily",
            name="numbering_resets_yearly",
            field=models.BooleanField(
                default=True,
                help_text="Счётчик протоколов обнуляется 1 января",
                verbose_name="нумерация сбрасывается в начале года",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalConditionProfile",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Основной", max_length=120, verbose_name="название"
                    ),
                ),
                (
                    "ranges",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="диапазоны"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="активен"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical профиль условий поверки",
                "verbose_name_plural": "historical профили условий поверки",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
