# Generated by Django 5.1.6 on 2026-09-14 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsitype",
            name="limits",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Для счётчиков воды: q_min, q_transition_a, q_transition_b, q_nominal, q_max, error_below_transition, error_above_transition. Читается apps.verification.calculators.water_meter.MeterLimits",
                verbose_name="метрологические характеристики",
            ),
        ),
        migrations.AddField(
            model_name="sitype",
            name="limits",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Для счётчиков воды: q_min, q_transition_a, q_transition_b, q_nominal, q_max, error_below_transition, error_above_transition. Читается apps.verification.calculators.water_meter.MeterLimits",
                verbose_name="метрологические характеристики",
            ),
        ),
    ]
