# Generated by Django 5.1.6 on 2026-09-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_historicalsitype_limits_sitype_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='название')),
                ('is_active', models.BooleanField(default=True, verbose_name='используется')),
            ],
            options={
                'verbose_name': 'район обслуживания',
                'verbose_name_plural': 'районы обслуживания',
                'ordering': ['name'],
            },
        ),
    ]
