# Generated by Django 5.1.6 on 2026-09-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_discount_percent', models.DecimalField(decimal_places=1, default=10, help_text='Вычитается из примерной цены на форме заявки, если заявитель выбрал слот, отмеченный сотрудником как приоритетный', max_digits=4, verbose_name='скидка за приоритетное время, %')),
                ('is_active', models.BooleanField(default=True, verbose_name='действует')),
            ],
            options={
                'verbose_name': 'настройка цен',
                'verbose_name_plural': 'настройки цен',
            },
        ),
        migrations.AddField(
            model_name='historicalmeasurementfamily',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='За единицу СИ. Показывается заявителю на форме заявки как приблизительная цена — точная считается менеджером', max_digits=9, verbose_name='цена поверки, ₽'),
        ),
        migrations.AddField(
            model_name='historicalmeasurementfamily',
            name='requires_time_slot',
            field=models.BooleanField(default=True, help_text='Включено у счётчиков — поверка идёт на месте у заявителя, время выезда согласуется. У приборов, которые сдаются в контору (весы, гири), выключите — заявителю на форме время не показывается', verbose_name='нужно выбирать время, не только дату'),
        ),
        migrations.AddField(
            model_name='measurementfamily',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='За единицу СИ. Показывается заявителю на форме заявки как приблизительная цена — точная считается менеджером', max_digits=9, verbose_name='цена поверки, ₽'),
        ),
        migrations.AddField(
            model_name='measurementfamily',
            name='requires_time_slot',
            field=models.BooleanField(default=True, help_text='Включено у счётчиков — поверка идёт на месте у заявителя, время выезда согласуется. У приборов, которые сдаются в контору (весы, гири), выключите — заявителю на форме время не показывается', verbose_name='нужно выбирать время, не только дату'),
        ),
    ]
