# Generated by Django 5.1.6 on 2026-09-15 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0002_employee_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='что сделать')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('status', models.CharField(choices=[('todo', 'К выполнению'), ('in_progress', 'В работе'), ('done', 'Выполнена'), ('cancelled', 'Отменена')], default='todo', max_length=12, verbose_name='статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочно')], default='normal', max_length=8, verbose_name='приоритет')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='срок')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Для загрузки сотрудников на неделю — без оценки задача в неё не попадает', max_digits=5, null=True, verbose_name='оценка, ч')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('recurrence', models.CharField(blank=True, help_text='Стандартное cron-выражение, например «0 6 1 * *» — раз в месяц. Пусто — разовая задача. См. apps.tasks.recurrence', max_length=60, verbose_name='повтор (cron)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='выполнена')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.employee', verbose_name='исполнитель')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='тип объекта')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to='core.employee', verbose_name='постановщик')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tasks.task', verbose_name='родительская задача')),
                ('recurrence_parent', models.ForeignKey(blank=True, help_text='Заполняется у задач, порождённых по расписанию', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurrence_instances', to='tasks.task', verbose_name='повторяется из')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ['due_date', '-priority', 'id'],
                'indexes': [models.Index(fields=['assignee', 'status'], name='tasks_task_assigne_7928f6_idx'), models.Index(fields=['content_type', 'object_id'], name='tasks_task_content_2bbe5a_idx')],
            },
        ),
    ]
