# Generated by Django 5.1.6 on 2026-09-15 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_district'),
        ('core', '0002_employee_telegram_chat_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=100, help_text='Меньше — выше в очереди на назначение', verbose_name='приоритет')),
                ('is_active', models.BooleanField(default=True, verbose_name='действует')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='catalog.district', verbose_name='район')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='district_assignments', to='core.employee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'закрепление района',
                'verbose_name_plural': 'закрепления районов',
                'ordering': ['district', 'priority'],
                'constraints': [models.UniqueConstraint(fields=('district', 'employee'), name='districtassignment_unique')],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('site', 'Форма на сайте'), ('phone', 'Телефон'), ('email', 'Email'), ('manual', 'Внесена вручную')], default='site', max_length=10, verbose_name='источник')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('routed', 'Подобран исполнитель'), ('confirmed', 'Подтверждена'), ('rejected', 'Отклонена'), ('spam', 'Спам / дубль')], default='new', max_length=10, verbose_name='статус')),
                ('contact_name', models.CharField(max_length=200, verbose_name='имя / организация')),
                ('contact_phone', models.CharField(blank=True, max_length=32, verbose_name='телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.CharField(max_length=350, verbose_name='адрес')),
                ('postal_code', models.CharField(blank=True, max_length=6, verbose_name='индекс')),
                ('fias_id', models.CharField(blank=True, max_length=64, verbose_name='ФИАС ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_address_confirmed', models.BooleanField(default=False, help_text='Снято — заявитель ввёл адрес вручную, район не распознан автоматически', verbose_name='адрес выбран из подсказки')),
                ('si_description', models.TextField(blank=True, verbose_name='что нужно поверить')),
                ('desired_date', models.DateField(blank=True, null=True, verbose_name='желаемая дата')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('reject_reason', models.CharField(blank=True, max_length=250, verbose_name='причина отклонения')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP заявителя')),
                ('honeypot_tripped', models.BooleanField(default=False, help_text='Заявка всё равно сохраняется — так проще смотреть, сколько спама отсеивается', verbose_name='поймана honeypot-полем')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='создана')),
                ('routed_at', models.DateTimeField(blank=True, null=True, verbose_name='подобран исполнитель')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='подтверждена')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to='core.employee', verbose_name='назначенный исполнитель')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='catalog.district', verbose_name='район')),
                ('suggested_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_requests', to='core.employee', verbose_name='рекомендованный исполнитель')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='hub_request_status_831d54_idx')],
            },
        ),
    ]
