# Generated by Django 5.1.6 on 2026-09-15 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pricingsettings_historicalmeasurementfamily_price_and_more'),
        ('core', '0003_employee_telegram_link_code_and_more'),
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='desired_time',
            field=models.TimeField(blank=True, help_text='Заполняется, только если среди приборов заявки есть хотя бы один, требующий выбора времени (MeasurementFamily.requires_time_slot)', null=True, verbose_name='желаемое время'),
        ),
        migrations.AddField(
            model_name='request',
            name='discount_percent',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Снимок PricingSettings.priority_discount_percent на момент отправки', max_digits=4, verbose_name='применённая скидка, %'),
        ),
        migrations.AddField(
            model_name='request',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Снимок расчёта на момент отправки формы — по текущим ценам может отличаться, это ориентир заявителю, а не выставленный счёт', max_digits=10, null=True, verbose_name='примерная цена'),
        ),
        migrations.AddField(
            model_name='request',
            name='is_priority_slot',
            field=models.BooleanField(default=False, help_text='Заявитель выбрал дату/время, отмеченные сотрудником как приоритетные (apps.hub.models.EmployeeAvailability.is_priority) — даёт скидку', verbose_name='выбран приоритетный слот'),
        ),
        migrations.AlterField(
            model_name='request',
            name='si_description',
            field=models.TextField(blank=True, help_text='Список приборов теперь — RequestItem (family + количество); здесь только свободный текст, если заявитель что-то уточнил словами', verbose_name='что нужно поверить — доп. примечание'),
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='количество')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Снимок MeasurementFamily.price на момент отправки формы', max_digits=9, verbose_name='цена за единицу на момент заявки')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.measurementfamily', verbose_name='тип прибора')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hub.request', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'прибор в заявке',
                'verbose_name_plural': 'приборы в заявке',
            },
        ),
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('district', 'Выезд в своём районе'), ('trip', 'Командировка')], default='district', max_length=10, verbose_name='тип')),
                ('date', models.DateField(db_index=True, verbose_name='дата')),
                ('start_time', models.TimeField(blank=True, help_text='Пусто — весь день', null=True, verbose_name='с')),
                ('end_time', models.TimeField(blank=True, help_text='Пусто — весь день', null=True, verbose_name='по')),
                ('is_priority', models.BooleanField(default=False, help_text='Показывается заявителю со скидкой — это время сотруднику удобнее', verbose_name='приоритетное время')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to='core.employee', verbose_name='сотрудник')),
            ],
            options={
                'verbose_name': 'слот доступности сотрудника',
                'verbose_name_plural': 'слоты доступности сотрудников',
                'ordering': ['date', 'start_time'],
                'indexes': [models.Index(fields=['employee', 'date'], name='hub_employe_employe_db1d1c_idx')],
            },
        ),
    ]
