# Generated by Django 5.1.6 on 2026-09-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hub", "0002_request_desired_time_request_discount_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="request",
            name="consent_given",
            field=models.BooleanField(
                default=False,
                help_text="Отметка чекбокса на публичной форме — обязательна для отправки (ст. 9 152-ФЗ)",
                verbose_name="согласие на обработку персональных данных",
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Новая"),
                    ("routed", "Подобран исполнитель"),
                    ("confirmed", "Подтверждена"),
                    ("done", "Выполнена"),
                    ("cancelled", "Отменена"),
                    ("rejected", "Отклонена"),
                    ("spam", "Спам / дубль"),
                ],
                default="new",
                max_length=10,
                verbose_name="статус",
            ),
        ),
    ]
